USE Quran

GO

INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	1 	,N'سورة الفاتحة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	2 	,N'سورة البقرة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	3 	,N'سورة آل عمران')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	4 	,N'سورة النساء')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	5 	,N'سورة المائدة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	6 	,N'سورة الأنعام')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	7 	,N'سورة الأعراف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	8 	,N'سورة الأنفال')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	9 	,N'سورة التوبة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	10 	,N'سورة يونس')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	11 	,N'سورة هود')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	12 	,N'سورة يوسف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	13 	,N'سورة الرعد')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	14 	,N'سورة إبراهيم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	15 	,N'سورة الحجر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	16 	,N'سورة النحل')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	17 	,N'سورة الإسراء')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	18 	,N'سورة الكهف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	19 	,N'سورة مريم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	20 	,N'سورة طه')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	21 	,N'سورة الأنبياء')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	22 	,N'سورة الحج')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	23 	,N'سورة المؤمنون')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	24 	,N'سورة النور')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	25 	,N'سورة الفرقان')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	26 	,N'سورة الشعراء')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	27 	,N'سورة النمل')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	28 	,N'سورة القصص')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	29 	,N'سورة العنكبوت')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	30 	,N'سورة الروم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	31 	,N'سورة لقمان')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	32 	,N'سورة السجدة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	33 	,N'سورة الأحزاب')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	34 	,N'سورة سبأ')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	35 	,N'سورة فاطر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	36 	,N'سورة يس')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	37 	,N'سورة الصافات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	38 	,N'سورة ص')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	39 	,N'سورة الزمر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	40 	,N'سورة غافر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	41 	,N'سورة فصلت')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	42 	,N'سورة الشورى')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	43 	,N'سورة الزخرف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	44 	,N'سورة الدخان')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	45 	,N'سورة الجاثية')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	46 	,N'سورة الأحقاف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	47 	,N'سورة محمد')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	48 	,N'سورة الفتح')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	49 	,N'سورة الحجرات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	50 	,N'سورة ق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	51 	,N'سورة الذاريات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	52 	,N'سورة الطور')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	53 	,N'سورة النجم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	54 	,N'سورة القمر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	55 	,N'سورة الرحمن')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	56 	,N'سورة الواقعة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	57 	,N'سورة الحديد')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	58 	,N'سورة المجادلة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	59 	,N'سورة الحشر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	60 	,N'سورة الممتحنة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	61 	,N'سورة الصف')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	62 	,N'سورة الجمعة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	63 	,N'سورة المنافقون')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	64 	,N'سورة التغابن')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	65 	,N'سورة الطلاق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	66 	,N'سورة التحريم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	67 	,N'سورة الملك')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	68 	,N'سورة القلم')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	69 	,N'سورة الحاقة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	70 	,N'سورة المعارج')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	71 	,N'سورة نوح')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	72 	,N'سورة الجن')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	73 	,N'سورة المزمل')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	74 	,N'سورة المدثر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	75 	,N'سورة القيامة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	76 	,N'سورة الإنسان')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	77 	,N'سورة المرسلات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	78 	,N'سورة النبأ')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	79 	,N'سورة النازعات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	80 	,N'سورة عبس')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	81 	,N'سورة التكوير')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	82 	,N'سورة الإنفطار')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	83 	,N'سورة المطففين')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	84 	,N'سورة الانشقاق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	85 	,N'سورة البروج')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	86 	,N'سورة الطارق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	87 	,N'سورة الأعلى')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	88 	,N'سورة الغاشية')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	89 	,N'سورة الفجر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	90 	,N'سورة البلد')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	91 	,N'سورة الشمس')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	92 	,N'سورة الليل')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	93 	,N'سورة الضحى')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	94 	,N'سورة الشرح')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	95 	,N'سورة التين')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	96 	,N'سورة العلق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	97 	,N'سورة القدر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	98 	,N'سورة البينة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	99 	,N'سورة الزلزلة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	100 	,N'سورة العاديات')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	101 	,N'سورة القارعة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	102 	,N'سورة التكاثر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	103 	,N'سورة العصر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	104 	,N'سورة الهمزة')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	105 	,N'سورة الفيل')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	106 	,N'سورة قريش')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	107 	,N'سورة الماعون')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	108 	,N'سورة الكوثر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	109 	,N'سورة الكافرون')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	110 	,N'سورة النصر')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	111 	,N'سورة المسد')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	112 	,N'سورة الإخلاص')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	113 	,N'سورة الفلق')
INSERT [dbo].[Surahs] ([ID], [Name]) VALUES (	114 	,N'سورة الناس')


GO

INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	1	,1,N'Al-Fatiha')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	2	,1,N'Al-Baqara')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	3	,1,N'Aal-e-Imran')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	4	,1,N'An-Nisa')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	5	,1,N'Al-Maeda')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	6	,1,N'Al-Anaam')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	7	,1,N'Al-Araf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	8	,1,N'Al-Anfal')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	9	,1,N'At-Taubah')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	10	,1,N'Yunus')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	11	,1,N'Hud')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	12	,1,N'Yusuf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	13	,1,N'Ar-Rad')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	14	,1,N'Ibrahim')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	15	,1,N'Al-Hijr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	16	,1,N'An-Nahl')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	17	,1,N'Al-Isra')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	18	,1,N'Al-Kahf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	19	,1,N'Maryam')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	20	,1,N'Taha')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	21	,1,N'Al-Anbiya')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	22	,1,N'Al-Hajj')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	23	,1,N'Al-Mumenoon')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	24	,1,N'An-Noor')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	25	,1,N'Al-Furqan')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	26	,1,N'Ash-Shuara')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	27	,1,N'An-Naml')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	28	,1,N'Al-Qasas')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	29	,1,N'Al-Ankaboot')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	30	,1,N'Ar-Room')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	31	,1,N'Luqman')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	32	,1,N'As-Sajda')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	33	,1,N'Al-Ahzab')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	34	,1,N'Saba')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	35	,1,N'Fatir')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	36	,1,N'Ya Seen')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	37	,1,N'As-Saaffat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	38	,1,N'Sad')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	39	,1,N'Az-Zumar')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	40	,1,N'Ghafir')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	41	,1,N'Fussilat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	42	,1,N'Ash-Shura')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	43	,1,N'Az-Zukhruf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	44	,1,N'Ad-Dukhan')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	45	,1,N'Al-Jathiya')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	46	,1,N'Al-Ahqaf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	47	,1,N'Muhammad')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	48	,1,N'Al-Fath')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	49	,1,N'Al-Hujraat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	50	,1,N'Qaf')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	51	,1,N'Adh-Dhariyat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	52	,1,N'At-tur')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	53	,1,N'An-Najm')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	54	,1,N'Al-Qamar')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	55	,1,N'Ar-Rahman')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	56	,1,N'Al-Waqia')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	57	,1,N'Al-Hadid')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	58	,1,N'Al-Mujadila')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	59	,1,N'Al-Hashr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	60	,1,N'Al-Mumtahana')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	61	,1,N'As-Saff')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	62	,1,N'Al-Jumua')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	63	,1,N'Al-Munafiqoon')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	64	,1,N'At-Taghabun')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	65	,1,N'At-Talaq')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	66	,1,N'At-Tahrim')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	67	,1,N'Al-Mulk')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	68	,1,N'Al-Qalam')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	69	,1,N'Al-Haaqqa')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	70	,1,N'Al-Maarij')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	71	,1,N'Nooh')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	72	,1,N'Al-Jinn')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	73	,1,N'Al-Muzzammil')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	74	,1,N'Al-Muddathir')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	75	,1,N'Al-Qiyama')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	76	,1,N'Al-Insan')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	77	,1,N'Al-Mursalat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	78	,1,N'An-Naba')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	79	,1,N'An-Naziat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	80	,1,N'Abasa')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	81	,1,N'At-Takwir')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	82	,1,N'AL-Infitar')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	83	,1,N'Al-Mutaffifin')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	84	,1,N'Al-Inshiqaq')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	85	,1,N'Al-Burooj')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	86	,1,N'At-Tariq')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	87	,1,N'Al-Ala')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	88	,1,N'Al-Ghashiya')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	89	,1,N'Al-Fajr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	90	,1,N'Al-Balad')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	91	,1,N'Ash-Shams')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	92	,1,N'Al-Lail')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	93	,1,N'Ad-Dhuha')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	94	,1,N'Al-Inshirah')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	95	,1,N'At-Tin')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	96	,1,N'Al-Alaq')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	97	,1,N'Al-Qadr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	98	,1,N'Al-Bayyina')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	99	,1,N'Al-Zalzala')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	100	,1,N'Al-Adiyat')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	101	,1,N'Al-Qaria')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	102	,1,N'At-Takathur')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	103	,1,N'Al-Asr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	104	,1,N'Al-Humaza')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	105	,1,N'Al-fil')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	106	,1,N'Quraish')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	107	,1,N'Al-Maun')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	108	,1,N'Al-Kauther')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	109	,1,N'Al-Kafiroon')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	110	,1,N'An-Nasr')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	111	,1,N'Al-Masadd')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	112	,1,N'Al-Ikhlas')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	113	,1,N'Al-Falaq')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	114	,1,N'An-Nas')

GO


INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	1	,2,N'সূরা আল ফাতিহা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	2	,2,N'সূরা আল বাক্বারাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	3	,2,N'সূরা আল ইমরান')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	4	,2,N'সূরা আন নিসা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	5	,2,N'সূরা আল মায়েদাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	6	,2,N'সূরা আল আন-আম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	7	,2,N'সূরা আল আ’রাফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	8	,2,N'সূরা আল-আনফাল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	9	,2,N'সূরা আত তাওবাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	10	,2,N'সূরা ইউনুস')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	11	,2,N'সূরা হুদ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	12	,2,N'সূরা ইউসূফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	13	,2,N'সূরা রা’দ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	14	,2,N'সূরা ইব্রাহীম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	15	,2,N'সূরা হিজর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	16	,2,N'সূরা নাহল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	17	,2,N'সূরা বনী ইসরাঈল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	18	,2,N'সূরা কাহফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	19	,2,N'সূরা মারইয়াম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	20	,2,N'সূরা ত্বোয়া-হা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	21	,2,N'সূরা আম্বিয়া')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	22	,2,N'সূরা হাজ্জ্ব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	23	,2,N'সূরা আল মু’মিনূন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	24	,2,N'সূরা আন-নূর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	25	,2,N'সূরা আল-ফুরকান')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	26	,2,N'সূরা আশ-শো’আরা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	27	,2,N'সূরা নমল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	28	,2,N'সূরা আল কাসাস')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	29	,2,N'সূরা আল আনকাবুত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	30	,2,N'সূরা আর-রূম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	31	,2,N'সূরা লোকমান')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	32	,2,N'সূরা সেজদাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	33	,2,N'সূরা আল আহযাব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	34	,2,N'সূরা সাবা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	35	,2,N'সূরা ফাতির')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	36	,2,N'সূরা ইয়াসীন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	37	,2,N'সূরা আস-সাফফাত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	38	,2,N'সূরা ছোয়াদ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	39	,2,N'সূরা আল-যুমার')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	40	,2,N'সূরা আল-মু’মিন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	41	,2,N'সূরা হা-মীম সেজদাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	42	,2,N'সূরা আশ-শুরা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	43	,2,N'সূরা যুখরুফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	44	,2,N'সূরা আদ দোখান')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	45	,2,N'সূরা আল জাসিয়া')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	46	,2,N'সূরা আল আহক্বাফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	47	,2,N'সূরা মুহাম্মদ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	48	,2,N'সূরা আল ফাতহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	49	,2,N'সূরা আল হুজরাত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	50	,2,N'সূরা ক্বাফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	51	,2,N'সূরা আয-যারিয়াত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	52	,2,N'সূরা আত্ব তূর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	53	,2,N'সূরা আন-নাজম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	54	,2,N'সূরা আল ক্বামার')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	55	,2,N'সূরা আর রহমান')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	56	,2,N'সূরা আল ওয়াক্বিয়া')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	57	,2,N'সূরা আল হাদীদ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	58	,2,N'সূরা আল মুজাদালাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	59	,2,N'সূরা আল হাশর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	60	,2,N'সূরা আল মুমতাহিনা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	61	,2,N'সূরা আছ-ছফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	62	,2,N'সূরা আল জুমুআহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	63	,2,N'সূরা মুনাফিকুন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	64	,2,N'সূরা আত-তাগাবুন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	65	,2,N'সূরা আত্ব-ত্বালাক্ব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	66	,2,N'সূরা আত-তাহরীম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	67	,2,N'সূরা আল মুলক')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	68	,2,N'সূরা আল কলম')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	69	,2,N'সূরা আল হাক্বক্বাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	70	,2,N'সূরা আল মা’আরিজ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	71	,2,N'সূরা নূহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	72	,2,N'সূরা আল জিন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	73	,2,N' সূরা মুযযামমিল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	74	,2,N'সূরা আল মুদ্দাসসির')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	75	,2,N'সূরা আল ক্বেয়ামাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	76	,2,N'সূরা আদ-দাহর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	77	,2,N'সূরা আল মুরসালাত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	78	,2,N'সূরা আন-নাবা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	79	,2,N'সূরা আন-নযিআ’ত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	80	,2,N'সূরা আবাসা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	81	,2,N'সূরা আত-তাকভীর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	82	,2,N'সূরা আল ইনফিতার')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	83	,2,N'সূরা আত-তাতফীফ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	84	,2,N'সূরা আল ইনশিক্বাক্ব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	85	,2,N'সূরা আল বুরূজ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	86	,2,N'সূরা আত্ব-তারিক্ব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	87	,2,N'সূরা আল আ’লা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	88	,2,N'সূরা আল গাশিয়াহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	89	,2,N'সূরা আল ফজর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	90	,2,N'সূরা আল বালাদ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	91	,2,N'সূরা আশ-শামস')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	92	,2,N'সূরা আল লায়ল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	93	,2,N'সূরা আদ্ব-দ্বোহা')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	94	,2,N'সূরা আল ইনশিরাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	95	,2,N'সূরা ত্বীন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	96	,2,N'সূরা আলাক')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	97	,2,N'সূরা কদর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	98	,2,N'সূরা বাইয়্যিনাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	99	,2,N'সূরা যিলযাল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	100	,2,N'সূরা আদিয়াত')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	101	,2,N'সূরা কারেয়া')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	102	,2,N'সূরা তাকাসূর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	103	,2,N'সূরা আছর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	104	,2,N'সূরা হুমাযাহ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	105	,2,N'সূরা ফীল')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	106	,2,N'সূরা কোরাইশ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	107	,2,N'সূরা মাউন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	108	,2,N'সূরা কাওসার')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	109	,2,N'সূরা কাফিরুন')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	110	,2,N'সূরা নছর')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	111	,2,N'সূরা লাহাব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	112	,2,N'সূরা এখলাছ')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	113	,2,N'সূরা ফালাক্ব')
INSERT [dbo].[SurahNames] ([SurahNo],[LanguageID],[Name]) VALUES (	114	,2,N'সূরা নাস')

GO